name: Auto Vote

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read URL from QR Code and perform auto vote
      run: ./gradlew :main:compileJava
